export const FETCH_ALL_APPOINTMENTS_PENDING = "FETCH_ALL_APPOINTMENTS_PENDING";
export const FETCH_ALL_APPOINTMENTS_SUCCESS = "FETCH_ALL_APPOINTMENTS_SUCCESS";
export const FETCH_ALL_APPOINTMENTS_FAILED = "FETCH_ALL_APPOINTMENTS_FAILED";

export const FETCH_ONE_APPOINTMENT_PENDING = "FETCH_ONE_APPOINTMENT_PENDING";
export const FETCH_ONE_APPOINTMENT_SUCCESS = "FETCH_ONE_APPOINTMENT_SUCCESS";
export const FETCH_ONE_APPOINTMENT_FAILED = "FETCH_ONE_APPOINTMENT_FAILED";

export const ADD_APPOINTMENT_PENDING = "ADD_APPOINTMENT_PENDING";
export const ADD_APPOINTMENT_SUCCESS = "ADD_APPOINTMENT_SUCCESS";
export const ADD_APPOINTMENT_FAILED = "ADD_APPOINTMENT_FAILED";

export const REMOVE_APPOINTMENT_PENDING = "REMOVE_APPOINTMENT_PENDING";
export const REMOVE_APPOINTMENT_SUCCESS = "REMOVE_APPOINTMENT_SUCCESS";
export const REMOVE_APPOINTMENT_FAILED = "REMOVE_APPOINTMENT_FAILED";

export const UPDATE_APPOINTMENT_PENDING = "UPDATE_APPOINTMENT_PENDING";
export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS";
export const UPDATE_APPOINTMENT_FAILED = "UPDATE_APPOINTMENT_FAILED";

export const BASE_URL = "http://localhost:8000/appointments";
